spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: Carlos
    password: c3Qh3K7wrMtQt/lp
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081