spring:
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.format_sql: true
      hibernate.show_sql: false
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate.hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      hibernate.hbm2ddl.auto: true
      hibernate.globally_quoted_identifiers: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      
management:
  security:
    enabled: false 