spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:/ruta/a/tu/directorio/donde/guardar/testdb
    url: jdbc:h2:file:C:/work/basesDatosH2/Practica1/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true   # http://localhost:8081/h2-console
      #path: /dataBase
      #settings:
      #  web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081
       
management:
  security:
    enabled: false 