spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:C:/work/basesDatosH2/Practica1/testdb
    driver-class-name: org.h2.Driver
    username: eCity
    password: practica1Clic
  h2:
    console:
      enabled: true   # http://localhost:8081/h2-console
      #path: /dataBase
      #settings:
      #  web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: update

server:
  port: 8081