/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practicas1eCityclic;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.ecityclic.practicas1eCityclic.Application;
import com.ecityclic.practicas1eCityclic.helper.TextoHelper;

public class ApplicationTest {
    
	@Test
    public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        assertFalse("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
	

}
